version: "3.8"

services:
  stb_frontend:
    build: ./STB_Frontend
    container_name: stb_frontend
    ports:
      - "80:80"
    depends_on:
      - stb_backend

  stb_backend:
    build: ./STB_Backend
    container_name: stb_backend
    ports:
      - "5110:5110"
    environment:
      - NODE_ENV=production
